In [101]:
import numpy as np 
def gradient_descent(x,y):
    m_curr = b_curr = 0
    iterations = 1000
    learning_rate = 0.001
    n = len(x)
    for i in range(iterations):
        y_pred = m_curr * x + b_curr
        dm = -2/n * sum(x*(y-y_pred))
        db = -2/n * sum(y-y_pred)
        m_curr = m_curr - learning_rate * dm 
        b_curr = b_curr - learning_rate * db 
        cost = 1/n * sum(y-y_pred) * sum(y-y_pred)
        print('m {}, b {}, cost {}, iterations {} '.format(m_curr, b_curr,cost,  i))
        
x = np.array([6,4,3,5])
y = np.array([12, 8, 6, 10])
gradient_descent(x,y)


m 0.08600000000000001, b 0.018000000000000002, cost 324.0, iterations 0 
m 0.16814, b 0.03519, cost 295.4960999999999, iterations 1 
m 0.24659327000000003, b 0.051606360000000004, cost 269.49687564960004, iterations 2 
m 0.32152530215, b 0.06728380785, cost 245.78237108946962, iterations 3 
m 0.3930941598869, b 0.08225551251495, cost 224.1519405744856, iterations 4 
m 0.46145081139912875, b 0.096553154050938, cost 204.42255349160928, iterations 5 
m 0.5267394481225078, b 0.11020699044024397, cost 186.42724814593575, iterations 6 
m 0.5890977889392778, b 0.12324592142626091, cost 170.01372125811278, iterations 7 
m 0.6486573707220524, b 0.1356975494829549, cost 155.04304126224866, iterations 8 
m 0.7055438258356576, b 0.14758823804749052, cost 141.38847453877815, iterations 9 
m 0.7598771471822968, b 0.15894316713887463, cost 128.93441467036095, iterations 10 
m 0.8117719413492082, b 0.1697863864799562, cost 117.57540567880567, iterations 11 
m 0.8613376703928726, b 0.18014086623485343,

m 1.9201427859758036, b 0.3805516831682884, cost 0.0017971801867692763, iterations 491 
m 1.9201516810303294, b 0.3805092947281696, cost 0.0017967798557058038, iterations 492 
m 1.9201605750934718, b 0.3804669110094403, cost 0.0017963796133246529, iterations 493 
m 1.9201694681653676, b 0.38042453201158016, cost 0.0017959794596286677, iterations 494 
m 1.9201783602461526, b 0.3803821577340687, cost 0.0017955793946189539, iterations 495 
m 1.9201872513359615, b 0.3803397881763852, cost 0.001795179418296312, iterations 496 
m 1.9201961414349276, b 0.38029742333800876, cost 0.00179477953066052, iterations 497 
m 1.9202050305431837, b 0.3802550632184184, cost 0.00179437973171011, iterations 498 
m 1.920213918660861, b 0.38021270781709293, cost 0.001793980021443422, iterations 499 
m 1.9202228057880903, b 0.380170357133511, cost 0.0017935803998571365, iterations 500 
m 1.9202316919250009, b 0.38012801116715117, cost 0.001793180866948344, iterations 501 
m 1.9202405770717215, b 0.38008566991

m 1.9242330105072776, b 0.36106012266191534, cost 0.0016177948097491504, iterations 963 
m 1.9242414499515075, b 0.361019905322026, cost 0.0016174344277736943, iterations 964 
m 1.9242498884556944, b 0.3609796924618184, cost 0.0016170741260775295, iterations 965 
m 1.9242583260199433, b 0.3609394840807935, cost 0.0016167139046424212, iterations 966 
m 1.9242667626443586, b 0.36089928017845246, cost 0.0016163537634507818, iterations 967 
m 1.9242751983290451, b 0.36085908075429635, cost 0.001615993702484634, iterations 968 
m 1.9242836330741075, b 0.36081888580782634, cost 0.0016156337217260756, iterations 969 
m 1.9242920668796504, b 0.36077869533854373, cost 0.0016152738211572789, iterations 970 
m 1.9243004997457784, b 0.3607385093459498, cost 0.0016149140007602415, iterations 971 
m 1.9243089316725963, b 0.3606983278295459, cost 0.0016145542605172862, iterations 972 
m 1.9243173626602088, b 0.36065815078883345, cost 0.0016141946004105238, iterations 973 
m 1.9243257927087203, b 0.36

In [92]:
x

array([6, 4, 3, 5])

In [40]:
import pandas as pd 
df = pd.read_csv('gradient.csv')
df

MATH  CS
0    50   5
1    60   6
2    70   7
3    80   8
4    90   9
5   100  10
6   110  11
7   120  12
8   130  13
9   140  14

In [94]:
X = df.drop(['MATH'], axis = 'columns')
Y = df['MATH']

In [82]:
from sklearn.linear_model import LinearRegression 
model = LinearRegression()
train = model.fit(X,Y)

In [83]:
model.intercept_

array([1.42108547e-14])

In [84]:
model.coef_

array([[10.]])

In [102]:
x = np.array(X).reshape(1,len(X))
y = np.array(Y).reshape(1,len(Y))
gradient_descent(x,y)

m [0.5  0.72 0.98 1.28 1.62 2.   2.42 2.88 3.38 3.92], b [0.1  0.12 0.14 0.16 0.18 0.2  0.22 0.24 0.26 0.28], cost [ 2500.  3600.  4900.  6400.  8100. 10000. 12100. 14400. 16900. 19600.], iterations 0 
m [0.974   1.38672 1.862   2.3936  2.97432 3.596   4.24952 4.9248  5.6108
 6.29552], b [0.1948  0.23112 0.266   0.2992  0.33048 0.3596  0.38632 0.4104  0.4316
 0.44968], cost [2246.76   3086.9136 3969.     4844.16   5661.0576 6368.04   6915.5856
 7259.04   7361.64   7197.8256], iterations 1 
m [1.423352   2.00410272 2.6558     3.362432   4.10653152 4.869608
 5.63263712 6.376608   7.083128   7.73508512], b [0.2846704  0.33401712 0.3794     0.420304   0.45628128 0.4869608
 0.51205792 0.531384   0.544856   0.55250608], cost [2019.17219904 2646.95432607 3214.89       3666.544704   3956.49051241
 4055.19334416 3952.50613148 3659.282064   3206.730384   2643.30068204], iterations 2 
m [1.8493377  2.57579912 3.37022    4.20531584 5.05306035 5.88594718
 6.67827366 7.40739168 8.05486448 8.60746158

 0.00000000e+00 8.07793567e-28], iterations 130 
m [9.60703499 9.72934888 9.79999106 9.84615374 9.87804878 9.9009901
 9.91803279 9.93103448 9.94117647 9.94923858], b [1.921407   1.62155815 1.39999872 1.23076922 1.09756098 0.99009901
 0.90163934 0.82758621 0.76470588 0.7106599 ], cost [2.09760829e-03 6.43251802e-06 5.03191798e-09 9.12481688e-13
 3.36148301e-17 2.10519283e-22 8.07793567e-28 2.01948392e-28
 0.00000000e+00 8.07793567e-28], iterations 131 
m [9.60746917 9.72937707 9.79999196 9.84615376 9.87804878 9.9009901
 9.91803279 9.93103448 9.94117647 9.94923858], b [1.92149383 1.62156284 1.39999885 1.23076922 1.09756098 0.99009901
 0.90163934 0.82758621 0.76470588 0.7106599 ], cost [1.88512896e-03 5.51572982e-06 4.07585356e-09 6.90657380e-13
 2.34932295e-17 1.34468548e-22 8.07793567e-28 2.01948392e-28
 0.00000000e+00 8.07793567e-28], iterations 132 
m [9.60788077 9.72940316 9.79999276 9.84615377 9.87804878 9.9009901
 9.91803279 9.93103448 9.94117647 9.94923858], b [1.92157615 1.621567

 0.00000000e+00 0.00000000e+00], iterations 277 
m [9.61538136 9.72972973 9.8        9.84615385 9.87804878 9.9009901
 9.91803279 9.93103448 9.94117647 9.94923858], b [1.92307627 1.62162162 1.4        1.23076923 1.09756098 0.99009901
 0.90163934 0.82758621 0.76470588 0.7106599 ], cost [3.18695234e-10 9.81773488e-16 1.77304428e-22 1.81753553e-27
 1.81753553e-27 8.07793567e-28 2.01948392e-28 2.01948392e-28
 0.00000000e+00 0.00000000e+00], iterations 278 
m [9.61538153 9.72972973 9.8        9.84615385 9.87804878 9.9009901
 9.91803279 9.93103448 9.94117647 9.94923858], b [1.92307631 1.62162162 1.4        1.23076923 1.09756098 0.99009901
 0.90163934 0.82758621 0.76470588 0.7106599 ], cost [2.86412681e-10 8.41847042e-16 1.43514423e-22 1.81753553e-27
 1.81753553e-27 8.07793567e-28 2.01948392e-28 2.01948392e-28
 0.00000000e+00 0.00000000e+00], iterations 279 
m [9.61538169 9.72972973 9.8        9.84615385 9.87804878 9.9009901
 9.91803279 9.93103448 9.94117647 9.94923858], b [1.92307634 1.621621

 0.00000000e+00 0.00000000e+00], iterations 423 
m [9.61538461 9.72972973 9.8        9.84615385 9.87804878 9.9009901
 9.91803279 9.93103448 9.94117647 9.94923858], b [1.92307692 1.62162162 1.4        1.23076923 1.09756098 0.99009901
 0.90163934 0.82758621 0.76470588 0.7106599 ], cost [5.38777733e-17 1.75745588e-25 1.81753553e-27 1.81753553e-27
 1.81753553e-27 2.01948392e-28 2.01948392e-28 2.01948392e-28
 0.00000000e+00 0.00000000e+00], iterations 424 
m [9.61538461 9.72972973 9.8        9.84615385 9.87804878 9.9009901
 9.91803279 9.93103448 9.94117647 9.94923858], b [1.92307692 1.62162162 1.4        1.23076923 1.09756098 0.99009901
 0.90163934 0.82758621 0.76470588 0.7106599 ], cost [4.84202463e-17 1.47220378e-25 1.81753553e-27 1.81753553e-27
 1.81753553e-27 2.01948392e-28 2.01948392e-28 2.01948392e-28
 0.00000000e+00 0.00000000e+00], iterations 425 
m [9.61538461 9.72972973 9.8        9.84615385 9.87804878 9.9009901
 9.91803279 9.93103448 9.94117647 9.94923858], b [1.92307692 1.621621

 0.00000000e+00 0.00000000e+00], iterations 571 
m [9.61538462 9.72972973 9.8        9.84615385 9.87804878 9.9009901
 9.91803279 9.93103448 9.94117647 9.94923858], b [1.92307692 1.62162162 1.4        1.23076923 1.09756098 0.99009901
 0.90163934 0.82758621 0.76470588 0.7106599 ], cost [7.36727928e-24 2.47386780e-27 1.81753553e-27 1.81753553e-27
 1.81753553e-27 2.01948392e-28 2.01948392e-28 2.01948392e-28
 0.00000000e+00 0.00000000e+00], iterations 572 
m [9.61538462 9.72972973 9.8        9.84615385 9.87804878 9.9009901
 9.91803279 9.93103448 9.94117647 9.94923858], b [1.92307692 1.62162162 1.4        1.23076923 1.09756098 0.99009901
 0.90163934 0.82758621 0.76470588 0.7106599 ], cost [6.68933853e-24 2.47386780e-27 1.81753553e-27 1.81753553e-27
 1.81753553e-27 2.01948392e-28 2.01948392e-28 2.01948392e-28
 0.00000000e+00 0.00000000e+00], iterations 573 
m [9.61538462 9.72972973 9.8        9.84615385 9.87804878 9.9009901
 9.91803279 9.93103448 9.94117647 9.94923858], b [1.92307692 1.621621

 0.00000000e+00 0.00000000e+00], iterations 706 
m [9.61538462 9.72972973 9.8        9.84615385 9.87804878 9.9009901
 9.91803279 9.93103448 9.94117647 9.94923858], b [1.92307692 1.62162162 1.4        1.23076923 1.09756098 0.99009901
 0.90163934 0.82758621 0.76470588 0.7106599 ], cost [5.04870979e-27 2.47386780e-27 1.81753553e-27 1.81753553e-27
 1.81753553e-27 2.01948392e-28 2.01948392e-28 2.01948392e-28
 0.00000000e+00 0.00000000e+00], iterations 707 
m [9.61538462 9.72972973 9.8        9.84615385 9.87804878 9.9009901
 9.91803279 9.93103448 9.94117647 9.94923858], b [1.92307692 1.62162162 1.4        1.23076923 1.09756098 0.99009901
 0.90163934 0.82758621 0.76470588 0.7106599 ], cost [5.04870979e-27 2.47386780e-27 1.81753553e-27 1.81753553e-27
 1.81753553e-27 2.01948392e-28 2.01948392e-28 2.01948392e-28
 0.00000000e+00 0.00000000e+00], iterations 708 
m [9.61538462 9.72972973 9.8        9.84615385 9.87804878 9.9009901
 9.91803279 9.93103448 9.94117647 9.94923858], b [1.92307692 1.621621

 0.00000000e+00 0.00000000e+00], iterations 856 
m [9.61538462 9.72972973 9.8        9.84615385 9.87804878 9.9009901
 9.91803279 9.93103448 9.94117647 9.94923858], b [1.92307692 1.62162162 1.4        1.23076923 1.09756098 0.99009901
 0.90163934 0.82758621 0.76470588 0.7106599 ], cost [2.47386780e-27 2.47386780e-27 1.81753553e-27 1.81753553e-27
 1.81753553e-27 2.01948392e-28 2.01948392e-28 2.01948392e-28
 0.00000000e+00 0.00000000e+00], iterations 857 
m [9.61538462 9.72972973 9.8        9.84615385 9.87804878 9.9009901
 9.91803279 9.93103448 9.94117647 9.94923858], b [1.92307692 1.62162162 1.4        1.23076923 1.09756098 0.99009901
 0.90163934 0.82758621 0.76470588 0.7106599 ], cost [2.47386780e-27 2.47386780e-27 1.81753553e-27 1.81753553e-27
 1.81753553e-27 2.01948392e-28 2.01948392e-28 2.01948392e-28
 0.00000000e+00 0.00000000e+00], iterations 858 
m [9.61538462 9.72972973 9.8        9.84615385 9.87804878 9.9009901
 9.91803279 9.93103448 9.94117647 9.94923858], b [1.92307692 1.621621

 0.00000000e+00 0.00000000e+00], iterations 994 
m [9.61538462 9.72972973 9.8        9.84615385 9.87804878 9.9009901
 9.91803279 9.93103448 9.94117647 9.94923858], b [1.92307692 1.62162162 1.4        1.23076923 1.09756098 0.99009901
 0.90163934 0.82758621 0.76470588 0.7106599 ], cost [2.47386780e-27 2.47386780e-27 1.81753553e-27 1.81753553e-27
 1.81753553e-27 2.01948392e-28 2.01948392e-28 2.01948392e-28
 0.00000000e+00 0.00000000e+00], iterations 995 
m [9.61538462 9.72972973 9.8        9.84615385 9.87804878 9.9009901
 9.91803279 9.93103448 9.94117647 9.94923858], b [1.92307692 1.62162162 1.4        1.23076923 1.09756098 0.99009901
 0.90163934 0.82758621 0.76470588 0.7106599 ], cost [2.47386780e-27 2.47386780e-27 1.81753553e-27 1.81753553e-27
 1.81753553e-27 2.01948392e-28 2.01948392e-28 2.01948392e-28
 0.00000000e+00 0.00000000e+00], iterations 996 
m [9.61538462 9.72972973 9.8        9.84615385 9.87804878 9.9009901
 9.91803279 9.93103448 9.94117647 9.94923858], b [1.92307692 1.621621